/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 54817bfc55dee8ccc16ccb7536835f19)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	JWT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "JWT_SECRET">> {}
}
